In [1]:
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline 


In [3]:
M = np.array([[0,1,0],[0,0,2],[3,0,0]])
N = np.array([[1,-1,1],[1,1,-1],[-1,1,1]])
print(M)
print(N)

[[0 1 0]
 [0 0 2]
 [3 0 0]]
[[ 1 -1  1]
 [ 1  1 -1]
 [-1  1  1]]


In [4]:
print(N*M)

[[ 0 -1  0]
 [ 0  0 -2]
 [-3  0  0]]


In [7]:
print(M*N)
print()
print(M.dot(N))

[[ 0 -1  0]
 [ 0  0 -2]
 [-3  0  0]]

[[ 1  1 -1]
 [-2  2  2]
 [ 3 -3  3]]


In [8]:
print(M@N)

[[ 1  1 -1]
 [-2  2  2]
 [ 3 -3  3]]


Quand on definit les matrices par des tableau, le produit matriciel ne se fait pas avec l'operation * mais @, * multiplie composante par composante, tandis que @ réalise l'opération usuelle. 

In [12]:
M = np.matrix("0 1 0; 0 0 2; 3 0 0")
N = np.matrix("1 -1 1; 1 1 -1; -1 1 1")
print(M)
print()
print(N)

[[0 1 0]
 [0 0 2]
 [3 0 0]]

[[ 1 -1  1]
 [ 1  1 -1]
 [-1  1  1]]


In [11]:
print(M*N)

[[ 1  1 -1]
 [-2  2  2]
 [ 3 -3  3]]


In [13]:
M = np.matrix("1 2 3 1; 1 5 7 2; 1 11 13 3")
print(M)

[[ 1  2  3  1]
 [ 1  5  7  2]
 [ 1 11 13  3]]


In [22]:
U = np.copy(M)
a,b = U[1,0]/U[0,0], U[2,0]/U[0,0]
U[1,:] = U[1,:]-a*U[0,:]
U[2,:] = U[2,:]-b*U[0,:]

In [25]:
print(U)


[[ 1  2  3  1]
 [ 0  3  4  1]
 [ 0  9 10  2]]


In [27]:
c = U[2,1]/U[1,1]
U[2,:] =  U[2,:] - c*U[1,:]
print(U)

[[ 1  2  3  1]
 [ 0  3  4  1]
 [ 0  0 -2 -1]]


In [28]:
print(M)

[[ 1  2  3  1]
 [ 1  5  7  2]
 [ 1 11 13  3]]


Pivot de gauss ! 

On garde une trace de M ! 


a, b represent le rapport entre L1 et L2 puis L1 et L3. c le raport entre L2-aL1 et L3-bL1 
U nous permet de representer le systeme et de pouvoir le manipuler sans changer la valeur de la matrice M

In [31]:
A = np.matrix("1 2 3; 4 5 6; 7 8 9")
B = np.matrix("10; 11; 12")
print(A,"\n\n",B,"\n")
print(np.matrix(np.hstack([A,B])))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

 [[10]
 [11]
 [12]] 

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [41]:
def func1(n,m): 
    """
    renvoie une matrice en fonction d'une expression
    """
    l = [[0]*n]*m
    
    for i in range(n): 
        for j in range(m): 
            l[i][j] = 5 - abs(i-j)
    s = ''
    for i in range(n): 
        for j in range(m):
            s+=' '
            s+=str(l[i][j])
        s+= ';'
    return np.matrix(s)
print(func1(5,5))
            

ValueError: Rows not the same size.